LoupVaillant/Monocypher

tests/ed25519-donna/modm-donna-32bit.h
add /* FALLTHRU */ comments to silence warnings
=> add /* FALLTHRU */ comments to silence warnings

tests/self.c
clock() in time.h is specified in C89 and should thus be portable.
COMPARISON_DIFF_THRESHOLD was chosen based on observed values, which
reached a maximum at 3.
=> Test constant-timeness of comparison functions

man/3monocypher/crypto_chacha20_encrypt.3monocypher
=> Fix formatting on man page for crypto_chacha20_*

man/3monocypher/crypto_argon2i.3monocypher, man/3monocypher/crypto_key_exchange.3monocypher, man/3monocypher/crypto_sign.3monocypher, man/3monocypher/intro.3monocypher
Various things that I noticed while trying to use Monocypher.
=> Man page fixes

src/monocypher.c
=> Fix typo in comment

doc/man/man3/crypto_key_exchange.3monocypher
=> eterministically -> deterministically

doc/man/man3/crypto_lock.3monocypher
Not entirely sure the bit about ad length is an improvement!
=> crypto_lock manual tweaks

doc/man/man3/crypto_argon2i_general.3monocypher, doc/man/man3/intro.3monocypher
This also adds it to intro(3monocypher).
=> Add symlink for crypto_argon2i_general.3monocypher

doc/man/man3/crypto_poly1305.3monocypher
I didn't make any notes for this one in the big docs feedback issue (must have missed it), so please make sure you agree with my changes
=> Poly1305 manual tweaks

doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_x25519.3monocypher
my most ambitious review yet, this one gives crypto_x25519 a man page to itself... (like poly1305/chacha20/chacha20H)
=> Key exchange manual tweaks

doc/man/man3/crypto_chacha20_encrypt.3monocypher, doc/man/man3/crypto_lock_init.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher
=> Misc manual tweaks

doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_poly1305.3monocypher
=> Fix wrong or missing const in man pages

doc/man/man3/crypto_key_exchange.3monocypher
=> Deprecate return values

LICENCE.md
Changes have been made since 2017.
=> LICENCE: update copyright year

AUTHORS.md, doc/man/man3/intro.3monocypher
Related to git commits 6163d8195a3acf2e143d20843a602fd5fb7671d5 and
56b81ae4ec987ba39a2f0ec8b434a4f8efddfef9.
=> Remove remaining pieces of kex documentation

doc/man/man3/crypto_sign_init_first_pass_custom_hash.3monocypher
=> doc: custom hash: clean up C-only-isms

src/monocypher.c
This hopefully helps both auditing the code (by giving a clear
indication of what a function is supposed to be doing),
and trying to work with it (by minimizing the amount of time people need
to determine if a function is relevant to their interests).
---
This is basically just an assortment of things I wish I knew these before going into the code. I'm not entirely sure that `ge` stands for "group element", but that's what I suspect it means.
While already here, remove two spaces in front of semicolons.
=> Add some comments about what the EC functions do

doc/man/man3/crypto_argon2i.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_chacha20.3monocypher, doc/man/man3/crypto_curve_to_hidden.3monocypher, doc/man/man3/crypto_ietf_chacha20.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_verify16.3monocypher, doc/man/man3/crypto_x25519.3monocypher, doc/man/man3/intro.3monocypher
There goes all hope of RC1->3.1.0 already. I expect that there's a chance that may object to the change in f4a20a0 in particular; if so, I don't plan to argue about it and will just remove that.
=> Sweeping manual review nitpick fixes

LICENCE.md
Non-trivial contributions by everyone listed.
=> LICENCE.md: Bump everyone's year

doc/man/man3/crypto_argon2i.3monocypher
Continued from #167. I've taken the liberty to interpret the silence as a tacit "do whatever you want, I'm done".
=> argon2i: Warn about conequences of nb_iterations < 3

doc/man/man3/crypto_argon2i.3monocypher
Sparked by #190. I've added this as a PR so that we can bicker about the wording, but it *may* also be a reasonable stance to say that this is unnecessary.
=> argon2i: Note that all parameters influence output

doc/man/man3/crypto_sign.3monocypher
Fixes #189; see the discussion there for details.
(Apologies for the delay, I forgot for a bit that the onus to PR was on me and just kept wondering why Loup wasn't committing anything.)
=> doc: clarify signature malleability in crypto_sign

doc/man/man3/crypto_key_exchange.3monocypher
Closes #230. May need some rewording.
=> doc: Mention hashing the public keys

.github/workflows/ci.yml, README.md
Since Github Actions on Ubuntu is free for Open Source, why not use it? :)
=> Add Github Actions CI, following the instructions from the readme.md to run basic tests. Add CI badge for Github Actions to readme.md.
