README.md
Turns out, [Debian stretch ships with 1.0.11](https://packages.debian.org/stretch/libsodium18), which lacks the required `crypto_stream_xchacha20_xor_ic` function.
=> Document minimum libsodium version for test suite

tests/self.c
This fixes building on OpenBSD 6.1, which ships with GCC 4.2.1. Trying
to build tests/self.c failed because it does not permit initializing a
const value from another const value.
The local const variables have been replaced with macros.
This fixes #9.
---
**Note**: `p_sha512()` had "Blake2b block size" in the comment. This felt off to me, but I kept it and used the `BLAKE2B_BLOCK_SIZE` macro instead of creating a `SHA512_BLOCK_SIZE` macro.
I also had to move the explanatory comments to a separate line, else the 80 column constraint would've been violated in about half of the cases.
=> self: Initialize const values from macros

tests/self.c
This can happen on 32-bit platforms and was reproduced on a 32-bit build
of Solaris 11.
=> Fix Chacha20 ctr test when size_t < u64

man/3monocypher/crypto_key_exchange.3monocypher, src/monocypher.c, src/monocypher.h
1. Change param "shared_secret" in crypto_x25519 to "raw_shared_secret" to aid quick identification of the difference between it and crypto_key_exchange; the "key" vs. "secret" gets lost easily because of the shared prefix "shared_".
2. Fix not having punctuation as a separate word in macro.
=> Minor improvements to crypto_key_exchange man page

makefile
This is required for the `DESTDIR` variable to actually work and create the necessary tree.
=> Create all installation directories

doc/man/man3/style.css
It turns out that they are still used when doing e.g. .Bf Em (yiedling a
block \<div class="emph"\>...\</div\>).
I also forgot to add centering, which I've had on my GitHub Pages of
the HTML exported man pages.
=> Add old CSS class names; add centering

doc/man2html.sh
We strip the ".3monocypher" from the filename, so the `-Oman` argument needs to reflect that.
=> Fix link generation in HTML man page conversion

doc/man2html.sh
A commit in mandoc earlier this year subtly broke the `-O` parsing.
Multiple instances of `-O` do not get parsed, so all options have to be passed into the same `-O` with comma separation as intended.
Presumably caused by [this commit](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/mandoc/main.c.diff?r1=1.185&r2=1.186&f=h).
=> Fix mandoc invocation for recent mandoc versions

makefile
rm returns non-zero when the target file does not exist. This is possible when e.g. a user only does `install-doc` but not `install`.
=> make uninstall should not fail on partial installs

doc/man/man3/crypto_argon2i.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_chacha20_encrypt.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_lock_init.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_wipe.3monocypher, doc/man/man3/intro.3monocypher
This includes adjustments in other manual pages and examples, telling
the user to use crypto_wipe.
=> Add man page for crypto_wipe

doc/man/man3/crypto_argon2i.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_chacha20_H.3monocypher, doc/man/man3/crypto_chacha20_encrypt.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_memcmp.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_verify16.3monocypher, doc/man/man3/crypto_wipe.3monocypher, doc/man/man3/crypto_x25519.3monocypher, doc/man/man3/intro.3monocypher
I have tried to avoid minor phrasing changes because that's an infinitely long road that everyone is sick of
I checked every function signature in the docs match monocypher.h, not all of them do
all sizes in args blocks are now, in bytes.
I compiled all the examples as C/C++ with -Wall -Wextra on GCC and /W4 on Windows. W4 gives some junk warnings about type conversions in monocypher.c, but nobody uses W4 (not even microsoft, many standard includes are not W4 clean...). I **didn't** actually run them and test the outputs
@LoupVaillant: to save you from trawling through today's spam on #58 I have added the unresolved issues as comments here
sorry about your inboxes btw.
=> More manual tweaks

doc/man/man3/intro.3monocypher
This is a very small copy paste error I noticed in https://monocypher.org/manual/#Timing_attacks
=> Fix copy-paste mistake in intro docs

doc/man/man3/crypto_x25519.3monocypher
This addresses #102.
This also adds a note that the public key function returns nothing, as is noted on crypto_key_exchange(3monocypher).
=> Deprecate return values in crypto_x25519

doc/man/man3/crypto_kex_x_init_client.3monocypher, doc/man/man3/crypto_kex_xk1_init_client.3monocypher, doc/man/man3/crypto_memcmp.3monocypher, doc/man/man3/crypto_sign.3monocypher
- There was some trailing whitespace on some of the lines of the new
pages that I hadn't noticed.
- There was a .PP instead of .Pp.
- There was a .Fa with no space after it.
This is just a cleanup; no content has been changed.
=> man: fix whitespace and macro invocation issues

makefile
This fixes building with gmake on Solaris 10,
and likely some other platforms with /bin/sh before POSIX standardized
$() for command substitution.
Addresses issue #120.
=> makefile: switch from $() to backticks

doc/man/man3/crypto_argon2i.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_chacha20_H.3monocypher, doc/man/man3/crypto_chacha20_encrypt.3monocypher, doc/man/man3/crypto_kex_x_init_client.3monocypher, doc/man/man3/crypto_kex_xk1_init_client.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_lock_init.3monocypher, doc/man/man3/crypto_memcmp.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_verify16.3monocypher, doc/man/man3/crypto_wipe.3monocypher, doc/man/man3/crypto_x25519.3monocypher
These changes make it easier for people who read a newer manual than the one they have. This could happen if a long-term stability Linux distribution ends up packaging Monocypher and backporting security fixes, but developers are reading the manual on the web.
The wording of each first sentence matches OpenBSD's for section 3 HISTORY sections.
=> Add HISTORY sections

doc/man/man3/crypto_kex_x_init_client.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/intro.3monocypher
- remove dead `.Pp` before `.Ss`
- use `.Dq` for quotes ("" doesn't get rendered with typographically correct quotes where possible)
=> manual: roff formatting fixes

README.md
Options 1 and 2 had colons after them, but option 3 didn't.
=> README: nitpicks

doc/man/man3/crypto_blake2b.3monocypher
Apparently there's an RFC for BLAKE2 now. We document this for XChaCha20 and Poly1305, so we should probably note it here, too.
=> Document BLAKE2 RFC

doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_x25519.3monocypher, doc/man/man3/intro.3monocypher
Related to git commit 6163d8195a3acf2e143d20843a602fd5fb7671d5.
It doesn't seem reasonable to ship a manual referencing functions that don't exist.
=> Clean up kex documentation removal

release.sh
This avoids some potential weirdness with whitespace in find and for.
Probably not going to be an actual concern, but it's just a nice general improvement.
=> Change release.sh to use find -exec

makefile
`return` only works in functions, so when I run `make check` with no
tests/vectors.h, I get
return 1
make: return: Command not found
make: *** [makefile:189: tests/vectors.h] Error 127
While I guess this does the job, the right thing to do here is `exit 1`.
=> Fix makefile rule when test/vectors.h is missing

src/monocypher.c
Just a minor thing I noticed. 2's complement will be the only signed integer representation in C2X (http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2412.pdf), but since Monocypher targets C99, I think it would be good to avoid relying on it.
=> Remove unnecessary dependency on 2's complement

makefile
This is my oversight and probably should've been done ages ago. The makefile never *actually* added the SONAME information into the shared library.
`$ objdump -p lib/libmonocypher.so` actually contains a `SONAME` after recompiling with this patch applied.
=> Add SONAME to shared library

src/monocypher.h
Monocypher uses nothing from `inttypes.h`, other than `stdint.h` that `inttypes.h` indirectly includes.
This seems to make `clang --target=wasm32` more amenable to Monocypher in a freestanding environment.
=> Use stdint.h over inttypes.h

makefile
The usefulness of both came to light up by packaging attempts. They're technically not required, but nice to have.
=> Two minor build system improvements

doc/man/man3/intro.3monocypher
This reverts commit df321b37cda1db5e8bd6fa76e4daf01ac087b865.
As it turns out,
groff (1.22.4) will spew complaints about the Lk formatting to stderr,
even though it's rendered perfectly fine.
=> Revert "intro: format link with .Lk"

doc/man/man3/test_examples.lua
I remember doing this by hand last time to make sure all the examples compiled and lots of them have broken since then, so maybe it makes sense to automate it
(with -Wno-discard-qualifiers)
```
asdf.c: In function ‘main’:
asdf.c:11:1: warning: implicit declaration of function ‘crypto_xchacha20_encrypt’; did you mean ‘crypto_xchacha20_ctr’? [-Wimplicit-function-declaration]
11 | crypto_xchacha20_encrypt(cipher_text, plain_text, 500, key, nonce);
| ^~~~~~~~~~~~~~~~~~~~~~~~
| crypto_xchacha20_ctr
asdf.c:36:33: error: ‘ctx’ undeclared (first use in this function); did you mean ‘ctr’?
36 |     ctr = crypto_xchacha20_ctr(&ctx, cipher_text+i, plain_text+i,
|                                 ^~~
|                                 ctr
asdf.c:36:33: note: each undeclared identifier is reported only …
```
=> Add a script to extract examples from man pages

doc/man/man3/crypto_chacha20.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/optional/crypto_hmac_sha512.3monocypher
Lots of the examples don't compile as C++ because they call crypto_wipe on const buffers
Having consts makes it a little clearer what's happening in the function calls that actually do the thing and these examples won't work by copy pasting them because they don't provide any data so IMO it's ok. It's not totally consistent right now so either way more changes are needed
=> Some examples fixes

doc/man/man3/crypto_sign_init_first_pass_custom_hash.3monocypher
Removes the non-portable arc4random(3) at least.
Still depends on the non-portable OpenBSD SHA-2 functions.
While there, fix CC-0 header to match reality.
---
Noticed while I was jotting down my thoughts on #144.
=> doc: use static key for custom hash example

dist.sh
Was just a one-line find(1) change, so one could argue removal of me in
the CC-0 header would've been cleaner,
but Loup wanted me to take credit for it (e-mail of Oct 21, 2019).
Correctly noted at the bottom in the CC-0 part.
I might need to write a script to consistency-check these at this rate.
=> dist.sh: Forgot copyright header for myself

doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/intro.3monocypher, doc/man/man3/optional/crypto_sha512.3monocypher
Prompted by an inquiry in #154.
---
The manual work this time is unusually deliberate in multiple ways.
**BLAKE2b/SHA-512**: The wording "BLAKE2b itself is not suitable" is a compromise between saying "*BLAKE2b is not suitable*" (which is an assertion I'm not comfortable making while PBKDF2 is still a thing that exists and can work with BLAKE2b as well as anything else—though one may certainly argue how appropriate PBKDF2 still is in times we bicker about Argon2 not having cache resistance) and "*BLAKE2b by itself is not suitable*" (which would correctly imply there are constructions that may be suitable, but then the question becomes "Why doesn't Monocypher just do this?", and that's one that would go far beyond what the manual is supposed to answer). I'm still not 100% happy with the …
=> Be more explicit about passwords in man pages

doc/man/man3/crypto_chacha20.3monocypher, doc/man/man3/crypto_hchacha20.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_sign_init_first_pass_custom_hash.3monocypher, doc/man/man3/crypto_x25519.3monocypher
It's unfortunate that we can't both tell users to wipe keys and illustrate which arguments are inputs and which ones are outputs at the same time, but that's just how it is.
Other TODO: `password` on the page for argon2i is uninitialized, and honestly there's something to be said there (since you're not guaranteed that `char*` -> `uint8_t*` is a safe cast, though usually in practice it is since `uint8_t` is normally an alias of `unsigned char`, but there's no guarantee in the C standard as far as I know).
=> Examples: const correctness

doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_x25519.3monocypher, tests/test.c
As discussed with Loup via e-mail, document and create a test for overlapping the shared_key & your_secret_key buffers for crypto_key_exchange().
Useful as in my application, there's no reason to keep around the secret key after obtaining a shared key, avoiding locking and wiping an extra buffer.
=> Document & test overlapping of key_exchange.

tests/test.c
Found through reading the patch to #159 and realizing that the typo was copied from surrounding code. See https://www.lexico.com/definition/overlap: “verb (overlaps, overlapping, overlapped)”
Completely trivial change, thus does not require changing file header.
=> tests: fix typo in messages

doc/extract_examples.sh, doc/man/man3/crypto_argon2i.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_chacha20.3monocypher, doc/man/man3/crypto_hchacha20.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_poly1305.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_x25519.3monocypher, doc/man/man3/optional/crypto_hmac_sha512.3monocypher, doc/man/man3/optional/crypto_sha512.3monocypher
I'm just doing this to crypto_lock.3monocypher right now to see if this is an improvement.
While already there, I've taken a few other liberties for clarification (use `else` with `crypto_unlock` because there's not enough outer structure to suggest just `return -1` with no cleanup or `goto clean` so that it doesn't look like it's dangling into the decryption-good part anyway; there are contexts other than sending stuff over the network).
So far, I'm not really convinced of any of those changes though and do mildly believe that the status quo is better:
- The `random_bytes` introduction is kind of wordy and just triplicates the usual hint to generate randomness with the OS (once in the intro, once in the description for the `nonce` argument, once in the new paragraph).
- The additional …
=> Add random_bytes() to crypto_lock examples

doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_x25519.3monocypher
While already there, hoist the explanation about contributory behavior from RETURN VALUES to the main DESCRIPTION section. The only reason it was in RETURN VALUES is because of historical reasons; we used to justify why the return value was deprecated there, so the position of the explanation made sense before removal of the return value.
=> doc: contributory behavior may be required sometimes

doc/man/man3/crypto_sign.3monocypher, doc/man/man3/crypto_sign_init_first_pass.3monocypher
While already there, add a very sternly worded warning about omitting the first pass that will *appear* to work but will, in fact, just repeat the Sony PlayStation 3 ECDSA nonce disaster with EdDSA instead.
RFC 8032 § 8.7 already hates Monocypher's guts for providing this risky interface at all, so we might as well use it for good: By showing how it can be used to mitigate power analysis attacks.
The wording is such that crypto_sign.3monocypher redirects to crypto_sign_init_first_pass.3monocypher for how to mitigate power-related side channels; crypto_ed25519_sign_init_first_pass.3monocypher already points to crypto_sign_init_first_pass.3monocypher wholesale anyway.
I've intentionally broken the rule that crypto_sign_init_first_pass.3monocypher *only* talks about BLAKE2b in this specific …
=> doc: more details on mitigating power side channels in EdDSA

src/monocypher.h
This fixes symbol compatibility if you have a project the compiles C and C++ separately
=> Add extern C if C++ presents

dist.sh, tests/gen/elligator-direct.py, tests/gen/elligator-inverse.py
There's a *lot* of other environmental damage that can't really be avoided, so reprodicibility depends on the exact setup used to generate the tarball anyway:
- at least OpenBSD sed(1) apparently munges the README *slightly* differently
- mandoc(1) versions *must not* differ or the HTML generated by doc2html will differ
- the operating system reported in mandoc(1) *must not* differ or the HTML generated by doc2html will differ
- probably more that I didn't catch after giving up at cross-OS reproducibility
So for anyone to be able to actually reproduce a release tarball, they need to know the exact setup. Perhaps building on a specific public Docker image and specifying this might be the easiest way to fixate and publicize this.
=> Make tarball generation reproducible

doc/man/man3/intro.3monocypher
Note that Solaris botched it in 11.3.9 and only made it good in 11.3.14. As far as I can tell, this has been long enough ago (more than two years at least, which matches FreeBSD fixing arc4random) that we can just put it in without reservation.
Note I've very intentionally overshot the requirements of #180. While macOS is probably the most relevant target (and hence earning Monocypher the questionable honor of being assigned a MON-01-001), this indicates that people scan for specific operating systems. While I've been operating under the assumption that programmers would know what their target OSes support, I figured we might as well take this chance to be very explicit about other, more niche operating systems, in hopes that people will test portability to more platforms.
=> intro: macOS, illumos and Solaris have arc4random_buf(3)

doc/man/man3/advanced/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_sign.3monocypher
Did some dumpster diving to figure this out. In retrospect, I'm surprised there wasn't a major version spike after this, but it's not like signatures generated by abusing signature malleability ever happen with legitimate signers in the first place.
There doesn't seem to be a good term to refer to a signature that is valid but has a greater *S* value than *L* without dragging the whole explanation of EdDSA in.
---
Change introduced in 974e55d21c1fac7a2e21f91cb7174601b653180a and
24f4be7acc3ec7ff613715a7a97597e587f6d6d8.
The actual reasons to introduce this were actually performance-related.
Sparked by #189.
=> HISTORY: note 2.0.5 rejecting modified signatures

tests/gen/elligator.py
See something, do something, etc. This one-character fix is obviously trivial enough not to be able to be copyrighted; notices on top left alone accordingly.
=> elligator.py: fix comment typo

doc/man/man3/advanced/crypto_ietf_chacha20.3monocypher
IETF ChaCha20 has a 32-bit counter. This means a practical limit of 256 GiB of data for each nonce. Additionally, IETF QUIC seems to require being able to handle 0xffffffff (I-D.draft-ietf-quic-tls-33 §&nbsp;5.4.4), thus getting very close to the overflow, though not triggering it.
Unlike libsodium and other libraries, we do not have the option to panic and take down whatever process is running the code and triggering the overflow condition because Monocypher is neither allowed to use the C standard library nor allowed to invoke undefined behavior to cause a crash; the applicable RFC provides no guidance what to do in this case, either.
Therefore, staying within the (nonce, counter) limits is necessarily application responsibility; it is an invariant that, when voided, Monocypher is …
=> crypto_ietf_chacha20: note nonce overflow handling

AUTHORS.md, README.md, doc/man/man3/advanced/crypto_chacha20.3monocypher, doc/man/man3/advanced/crypto_hchacha20.3monocypher, doc/man/man3/advanced/crypto_ietf_chacha20.3monocypher, doc/man/man3/advanced/crypto_poly1305.3monocypher, doc/man/man3/advanced/crypto_sign_init_first_pass.3monocypher, doc/man/man3/crypto_blake2b.3monocypher, doc/man/man3/crypto_key_exchange.3monocypher, doc/man/man3/crypto_lock.3monocypher, doc/man/man3/crypto_sign.3monocypher, doc/man/man3/deprecated/crypto_chacha20_encrypt.3monocypher, doc/man/man3/intro.3monocypher
Inspired by [this tweet by Jean-Philippe Aumasson](https://twitter.com/veorq/status/1396728032883322884). I believe it makes a positive impression to actually spell names correctly.
I didn't touch the code mainly for reasons of not intruding upon @LoupVaillant's territory, but it may be reasonable to also adjust comments and text case output as well.
=> Canonicalize spellings of algorithms

AUTHORS.md, src/deprecated/aead-incr.c, src/deprecated/aead-incr.h, src/deprecated/chacha20.c, src/deprecated/chacha20.h, src/monocypher.c, src/monocypher.h, src/optional/monocypher-ed25519.c, src/optional/monocypher-ed25519.h
Minimal change to permit Monocypher to be compiled as C++ and wrapped in a namespace, to prevent symbol name collisions (#224). I have verified that this works, in [a branch of my monocypher-cpp project](https://github.com/snej/monocypher-cpp/commit/adae8d327f16760c8feab6838f1999ea07409ea6).
If the preprocessor symbol `MONOCYPHER_CPP_NAMESPACE` is defined, the Monocypher headers will be wrapped in a C++ namespace instead of in `extern "C"`. The name of the namespace is the value of the symbol.
Using this feature requires also compiling monocypher.c as C++ in the same namespace, for instance by using a C++ source file wrapping the C one:
```
// monocypher.cpp
#define MONOCYPHER_CPP_NAMESPACE monocypher
namespace MONOCYPHER_CPP_NAMESPACE {
}
```
(Such a source file could be added here as …
=> Allow API to be put in a C++ namespace

doc/man/man3/crypto_x25519.3monocypher
#232 but for `crypto_x25519`. Hopefully the formatting is correct this time around.
=> doc/x25519: Mention hashing the public keys

makefile
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html:
> AR -  Archive-maintaining program; default ‘ar’.
=> makefile: fix cross-compilation

doc/man/man3/crypto_sign.3monocypher
You might disagree with some of the commits here, so I've split them up into logical units.
In re #240 pending the new `crypto_sign_safe()` and subsequent move to `advanced/` + deprecation warning.
=> crypto_sign doc hotfix: Miscellaneous improvements

doc/crypto_argon2.3monocypher, doc/crypto_blake2b.3monocypher, doc/crypto_chacha20_djb.3monocypher, doc/crypto_ed25519_sign.3monocypher, doc/crypto_eddsa_sign.3monocypher, doc/crypto_sha512.3monocypher, makefile
I cleaned out some leftover lint from the documentation overhaul; details in the respective commit messages.
The \& in crypto_eddsa_sign.3monocypher because Rs gets parsed as a non-existent macro otherwise and thus removed out of existence
@LoupVaillant `crypto_ed25519_sign.3monocypher` needs your copyright after merging because you copied the UB caveat everywhere
=> Manual fixes and a copyright note

doc/crypto_argon2.3monocypher
Closes: #264 
Fixes these issues, by allowing password array to autosize, and then making sure to drop the \0 character when determining the size of the string, and also reorders the crypto_argon2_inputs field designators to remove a warning.
```
main.cpp:83:24: error: initializer-string for char array is too long, array size is 14 but initializer has size 15 (including the null terminating character)
uint8_t password[14] = "Okay Password!";
^~~~~~~~~~~~~~~~
main.cpp:87:5: warning: ISO C++ requires field designators to be specified in declaration order; field 'pass_size' will be initialized after field 'salt' [-Wreorder-init-list]
.salt      = salt,                 /* Salt for the password */
^~~~~~~~~~~~~~~~~
```
=> Update crypto_argon2.3monocypher - fixes errors and warnings that can lead to the incorrect solution

src/monocypher.c
This came out of adding these compile options:
`-Werror -Wall -Wextra -Wshadow -Wconversion -Wno-deprecated-declarations -Wno-unused-parameter`
And finding this one error:
```
$ make CC="clang -Werror -Wall -Wextra -Wshadow -Wconversion -Wno-deprecated-declarations -Wno-unused-parameter"
clang -Werror -Wall -Wextra -Wshadow -Wconversion -Wno-deprecated-declarations -Wno-unused-parameter -pedantic -Wall -Wextra -O3 -march=native -I src -I src/optional -fPIC -c -o lib/monocypher.o src/monocypher.c
src/monocypher.c:881:40: error: implicit conversion loses integer precision: 'u64' (aka 'unsigned long long') to 'u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
u32  index     = lane * lane_size + (u32)ref;
~~~~~       ~~~~~~~~~~~~~~~~~^~~~~~~~~~
1 error generated.
make: *** …
```
=> make implicit typecast explicit

src/optional/monocypher-ed25519.c
This line of code looked like an out of bounds access within the context of the function.
However, it's a static function and the size of secret_key at all the caller locations was 64
=> Fix problamatic line
